### PR TITLE
Add unicode support (TrieNode and Text importer)

### PR DESCRIPTION
**Pull request by alanpoulain**
I've added Unicode support to TrieNode and Text importer.
However since the commit https://github.com/loophp/phptree/commit/ed4ff23470313dcd43b1b8a26460ba78c1e59917, the project seems broken.
Do you plan to fix it and make a new release?

### CODE REVIEW

**Comment by alanpoulain** [comment]
Please don't, friendly ping @drupol :slightly_smiling_face:

**Comment by drupol** [comment]
Why not, are you interested into being maintainer?

**Comment by drupol** [comment]
OK, adding you as maintainer! Thanks :)

**Comment by drupol** [comment]
Job done! Welcome mate :)

**Comment by alanpoulain** [comment]
Thanks :slightly_smiling_face:

**Pull request merged**
